spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskforge
    username: taskforge
    password: changeme
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

spring.flyway:
  enabled: true
  baseline-on-migrate: true

taskforge:
  security:
    jwt:
      secret: clave-super-mega-hiper-larga-1234567890
      expiration-ms: 3600000

server:
  port: 8080